# .gitpod.yml
tasks:
  - name: Install Rust tools
    init: |
      # This runs only once when the workspace is first created.
      rustup-init -y
      source "$HOME/.cargo/env"
      echo "✅ Rust is ready!"
    command: |
      # This runs every time you start the workspace.
      source "$HOME/.cargo/env"
      cargo install cross
      echo "✅ cross is installed and ready to use!"

# This ensures VS Code extensions for Rust are installed.
vscode:
  extensions:
    - rust-lang.rust-analyzer

# (type -p wget >/dev/null || (sudo apt-get update && sudo apt-get install wget -y)) \
# && sudo mkdir -p -m 755 /etc/apt/keyrings \
# && wget -qO- https://cli.github.com/packages/githubcli-archive-key.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-key.gpg > /dev/null \
# && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-key.gpg \
# && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-key.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
# && sudo apt-get update \
# && sudo apt-get install gh -y


# # 1. Create a git tag (e.g., v1.0.0)
# git tag v1.0.0
# git push origin v1.0.0

# # 2. Create the release and upload your file(s)
# gh release create v1.0.0 ./target/x86_64-unknown-linux-gnu/release/biome --notes "My first manual release"